# Exercise the unit tests

name: bowling unit testing

on:
  workflow_dispatch: {}
  push: {}

permissions:
  contents: read

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
      - run: echo hello
