[project]
name = "bowling"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["typer>=0.16.0"]

[dependency-groups]
dev = ["pytest>=8.3.5"]

[project.scripts]
score = "main:score"
