# Exercise the unit tests

name: bowling unit testing

on:
  workflow_dispatch: {}
  push: {}

permissions:
  contents: read

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
            python-version: '3.x'
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Run unit tests
        run: uv run pytest tests/test_bowling.py

